### ISSUE TITLE
rake bootstrap failing with ruby 2.2.0

### ISSUE THREAD

**Issue by andreamazz** [CocoaPods/Rainforest#38]
Hi all. 
While setting up Rainforest on a fresh install with ruby `2.2.0` I noticed that json 1.7.7 fails, as stated [here](https://github.com/flori/json/issues/229).  
Using ruby `2.1.2` fixes the issue, maybe the README should point this out, what do you think?

**Comment by segiddins** [comment]
I'm pretty sure we have a .ruby_version?

**Comment by andreamazz** [comment]
This repo doesn't seem to have one.

**Comment by segiddins** [comment]
Ah yeah json 1.7.7 doesn't compile on 2.2, I've needed to manually patch it to work. I just recommend using system ruby for CocoaPods development, honestly.

**Comment by smileyborg** [comment]
I just ran into this same issue; perhaps it would be a good idea to specify which Ruby version(s) should be used when running `rake bootstrap` in the README?

Switching to `ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]` worked for me, with the exception of this failure:

```
Bootstrapping Molinillo
rake --no-search bootstrap
/Users/tfox1/.rvm/gems/ruby-2.1.2@global/bin/bundle

--------------------------------------------------------------------------------
Installing gems
--------------------------------------------------------------------------------

bundle install
Undefined local variable or method `install_if' for Gemfile
        from /Users/tfox1/Developer/Forks/Rainforest/Molinillo/Gemfile:17
rake aborted!
Command failed with status (4): [bundle install...]
/Users/tfox1/Developer/Forks/Rainforest/Molinillo/Rakefile:9:in `block in <top (required)>'
/Users/tfox1/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/tfox1/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => bootstrap
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [rake --no-search bootstrap...]
/Users/tfox1/Developer/Forks/Rainforest/Rakefile:93:in `block (3 levels) in <top (required)>'
/Users/tfox1/Developer/Forks/Rainforest/Rakefile:90:in `chdir'
/Users/tfox1/Developer/Forks/Rainforest/Rakefile:90:in `block (2 levels) in <top (required)>'
/Users/tfox1/Developer/Forks/Rainforest/Rakefile:89:in `each'
/Users/tfox1/Developer/Forks/Rainforest/Rakefile:89:in `block in <top (required)>'
/Users/tfox1/Developer/Forks/Rainforest/Rakefile:50:in `block in <top (required)>'
Tasks: TOP => bootstrap_repos
(See full trace by running task with --trace)
```

I fixed the above issue by commenting out Line 17 (and the corresponding `end`) in Molinillo's Gemfile:

```ruby
install_if RUBY_VERSION >= '2.0.0' do
```

Not sure what the issue causing that is though.

**Comment by segiddins** [comment]
`install_if` is a bundler 1.10 feature
